language: php
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.9.0-rc3
    - COMPOSER_VERSION=1.4.1
    - COVERALLS_VERSION=v1.0.0
  matrix:
    - MAGENTO_VERSION=1.9.1.0
    - MAGENTO_VERSION=1.8.1.0
    - MAGENTO_VERSION=1.7.0.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo "MAGENTO_VERSION=$MAGENTO_VERSION" >> .env

script:
    - scripts/test.sh

after_success:
    - php composer.phar require satooshi/php-coveralls
    - travis_retry php vendor/bin/coveralls -v
